apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-subgraph-reviews
  namespace: subgraph-app
spec:
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    type: subgraph-reviews